GPU: 
  gpu_idx: 1

PROBLEM:
  # run_type: "regression" 
  run_type: "classification" 

  interp_method: "linear" # INN
  # interp_method: "nonlinear" # INN; to be updated
  # interp_method: "MLP"

DATA:
  ## ----------- regression data -------------
  # data_name : '1D_1D_sine'  
  # data_name : '1D_1D_exp' 
  # data_name : "1D_2D_sine_exp"
  # data_name : '2D_1D_sine'
  # data_name : '2D_1D_exp'
  # data_name : '8D_1D_physics' # borehole equation
  # data_name : 'IGAMapping2D' # for IGA inverse mapping; multi-CAD-patch C-IGA paper

  ## ----------- classification data -------------
  # data_name : 'spiral'
  data_name : 'mnist'
  # data_name : 'fashion_mnist'




  


  