MODEL_PARAM: 
  
  ## INN linear
  nmode : 1
  nelem : 10

  ## INN nonlinear
  s_patch : 2
  alpha_dil: 20
  p_order: 2
  radial_basis : "cubicSpline" # Activataion functions
  # radial_basis : 'gaussian1'
  INNactivation : 'polynomial'
  # INNactivation : 'sinusoidal'
  # INNactivation : 'exponential'
  # INNactivation : 'sigmoid'
  # INNactivation : 'tanh'
  # INNactivation : 'gelu'

  ## r-adaptivity
  radap : True
  radap_epoch: 2
  
  ## MLP
  nlayers : 2
  nneurons : 10
  # activation : "relu"
  activation : "sigmoid"

DATA_PARAM:
  input_col : [0]
  output_col : [1]
  bool_normalize: False # whether we normalize the input data or not
  bool_random_split : True # whether we randomly split the data or not
  data_size: 10_000
  split_ratio: [0.7,0.15,0.15]


TRAIN_PARAM:
  num_epochs_INN : 50
  num_epochs_MLP : 200
  batch_size : 128
  learning_rate : 1e-3
  bool_train_acc : True
  validation_period : 1

PLOT:
  bool_plot: True
  plot_in_axis: [0] # plot input axis
  plot_out_axis: [0] # plot output axis