MODEL_PARAM: 
  nmode : 30
  nelem : 1
  
  ## MLP
  nlayers : 3
  nneurons : 100
  # activation : "relu"
  activation : "sigmoid"

DATA_PARAM:
  nclass : 10
  bool_normalize : False 
  bool_image : True
  bool_random_split : False
  split_ratio : [60000,10000]

TRAIN_PARAM:
  num_epochs_INN : 20
  num_epochs_MLP : 40
  batch_size : 128
  learning_rate : 2e-4
  bool_train_acc : False
  validation_period : 5

PLOT:
  bool_plot: False
  